logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: DEBUG
server:
    port: 8080
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 1234
        url: jdbc:mysql://localhost:3306/HobbyDB?createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
    servlet:
       multipart:
           max-file-size: 10MB
           max-request-size: 10MB

    mvc:
        hiddenmethod:
          filter:
              enabled: true

cloudinary:
    api-key: 644675641924241
    api-secret: ${CLOUDINARY_API_SECRET}
    cloud-name: dpqbf79wg